export enum Key {
    KEY_ESC, KEY_TAB, KEY_CAPSLOCK, KEY_LSHIFT, KEY_RSHIFT, KEY_LCTRL, KEY_CONTEXTMENU,
    KEY_RCTRL, KEY_LALT, KEY_RALT, KEY_META, KEY_SPACE, KEY_ENTER, KEY_BACKSPACE, 
    KEY_0, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, 
    KEY_A, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, 
    KEY_H, KEY_I, KEY_J, KEY_K, KEY_L, KEY_M, KEY_N,
    KEY_O, KEY_P, KEY_Q, KEY_R, KEY_S, KEY_T, KEY_U,
    KEY_V, KEY_W, KEY_X, KEY_Y, KEY_Z,
    KEY_BACKQUOTE, KEY_SUBTRACT, KEY_EQUAL, KEY_COMMA, KEY_POINT, KEY_SEMICOLON,
    KEY_BSLASH, KEY_FSLASH, KEY_LBRACKET, KEY_RBRAKET,
    KEY_NUMPAD_0, KEY_NUMPAD_1, KEY_NUMPAD_2, KEY_NUMPAD_3, KEY_NUMPAD_4, KEY_NUMPAD_5,
    KEY_NUMPAD_6, KEY_NUMPAD_7, KEY_NUMPAD_8, KEY_NUMPAD_9, KEY_NUMPAD_COMMA, KEY_NUMPAD_ENTER,
    KEY_NUMPAD_ADD, KEY_NUMPAD_SUBTRACT, KEY_NUMPAD_MULTIPLY, KEY_NUMPAD_DIVIDE,
    KEY_NUMLOCK,
    KEY_MOUSE_LBUTTON, KEY_MOUSE_MBUTTON, KEY_MOUSE_RBUTTON,
    KEY_ARROW_UP, KEY_ARROW_DOWN, KEY_ARROW_LEFT, KEY_ARROW_RIGHT 
}

export enum CameraType {
    CAMERA_2D, CAMERA_3D
}

export enum CameraMovementMode {
    KEYBOARD_MOVEMENT_MODE, MOUSE_MOVEMENT_MODE
}

export enum GLShaderType {
    VERTEX = WebGL2RenderingContext.VERTEX_SHADER,
    FRAGMENT = WebGL2RenderingContext.FRAGMENT_SHADER
};

export enum GLBufferUsage {
    STATIC_DRAW = WebGL2RenderingContext.STATIC_DRAW,
    DYNAMIC_DRAW = WebGL2RenderingContext.DYNAMIC_DRAW
}

export enum GLType {
    FLOAT = WebGL2RenderingContext.FLOAT,
    MAT4 = WebGL2RenderingContext.FLOAT_MAT4,
    VEC3 = WebGL2RenderingContext.FLOAT_VEC3
}

export function GetSizeOfGLType(type : GLType) {
    switch(type) {
        case GLType.FLOAT: return Float32Array.BYTES_PER_ELEMENT;
        case GLType.MAT4: return Float32Array.BYTES_PER_ELEMENT * 16;
        case GLType.VEC3: return Float32Array.BYTES_PER_ELEMENT * 3;
    }
    
}
